---
version: 2.1

default:
  install: &poetry_install
    pkg_manager: poetry
    install_args: --no-ansi --with dev
  filter: &filter_tags_only
    filters:
      tags:
        # ONLY git tag compliant format: e.g. `0.0.1-alpha.01`
        only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
      branches:
        ignore: /.*/

# ----------------
# Orbs declaration
# ----------------

orbs:
  noos-ci: noosenergy/noos-ci@0.4.1

# --------------
# Pipeline tasks
# --------------

jobs:
  lint_package:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python_lint_package:
          <<: *poetry_install

  test_package:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python_test_package:
          <<: *poetry_install
      - store_test_results:
          path: ".pytest_results"

  build_wheel:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python_build_wheel:
          <<: *poetry_install
      - store_artifacts:
          path: dist
          destination: wheel

  publish_wheel:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python_publish_wheel:
          <<: *poetry_install

# -----------------
# Pipeline workflow
# -----------------

workflows:
  version: 2

  lint_test_build:
    jobs:
      - lint_package
      - test_package
      - build_wheel:
          requires:
            - lint_package
            - test_package

  publish:
    jobs:
      - approve_for_publishing:
          type: approval
          <<: *filter_tags_only
      - publish_wheel:
          requires:
            - approve_for_publishing
          context: PYPI_SHARED
          <<: *filter_tags_only
