---
version: 2.1

# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.14


# --------------
# Pipeline tasks
# --------------

jobs:

  lint-package:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python-lint-package:
          pkg-manager: poetry
          install-args: ''

  test-package:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python-test-package:
          pkg-manager: poetry
          install-args: ''
      - store_test_results:
          path: "."

  build-wheel:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python-build-wheel:
          pkg-manager: poetry
          install-args: ''
      - store_artifacts:
          path: dist
          destination: wheel

  publish-wheel:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python-publish-wheel:
          pkg-manager: poetry
          install-args: ''


# -----------------
# Pipeline workflow
# -----------------

workflows:

  version: 2

  lint-test-build:
    jobs:
      - lint-package
      - test-package
      - build-wheel:
          requires:
            - lint-package
            - test-package

  publish:
    jobs:
      - approve-for-publishing:
          type: approval
          filters:
            tags:
              # ONLY git tag compliant format: e.g. `0.0.1-alpha.01`
              only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
            branches:
              ignore: /.*/
      - publish-wheel:
          context: PYPI_SHARED
          requires:
            - approve-for-publishing
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
            branches:
              ignore: /.*/
