---
version: 2.1

default:
  install: &poetry-install
    pkg-manager: poetry
    install-args: ''
  filter: &filter-tags-only
    filters:
      tags:
        # ONLY git tag compliant format: e.g. `0.0.1-alpha.01`
        only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
      branches:
        ignore: /.*/

# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.15


# --------------
# Pipeline tasks
# --------------

jobs:

  lint-package:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python-lint-package:
          <<: *poetry-install

  test-package:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python-test-package:
          <<: *poetry-install
      - store_test_results:
          path: "."

  build-wheel:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python-build-wheel:
          <<: *poetry-install
      - store_artifacts:
          path: dist
          destination: wheel

  publish-wheel:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/python-publish-wheel:
          <<: *poetry-install


# -----------------
# Pipeline workflow
# -----------------

workflows:

  version: 2

  lint-test-build:
    jobs:
      - lint-package
      - test-package
      - build-wheel:
          requires:
            - lint-package
            - test-package

  publish:
    jobs:
      - approve-for-publishing:
          type: approval
          <<: *filter-tags-only
      - publish-wheel:
          requires:
            - approve-for-publishing
          context: PYPI_SHARED
          <<: *filter-tags-only
